name: 'deploy workflow'

on:
  release:
    types: [published]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.gAAD_Qi3QQygAP-OsAIqXtaxHxHvVuCv_AdROIlLxEU }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: "source"
