# Updated from template.yml
# Workflow will clean install of node dependencies, cache/restore them, build and test across different versions of node

name: Node.js CI

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: JSDoc Action
      uses: andstor/jsdoc-action@v1.2.0
      with:
        source_dir: ./source
        recurse: true
        output_dir: ./out
    - name: Run ESLint
      run: npm run lint
    

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: |
        npm install
        npm test
      env:
        CI: true
